name: frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to VPS for test
        uses: actions/checkout@v3
      - run: |
          docker compose down --rmi all
          docker compose -f docker-compose.yml up -d
